# Do I need the deploy?
deploy:
  provider: script
  # skip_cleanup: true
  # github_token: $GITHUB_TOKEN

language: python
python: 3.9

cache:
  pip: true

git:
  depth: false

branches:
  except:
    - "gh-pages"

before_install:
  - pip install --upgrade pip setuptools wheel

install:
  - pip install --upgrade memote

script:
  - git checkout "${TRAVIS_BRANCH}"
  - ./scripts/travis_deploy.sh
